/*
 * This file is generated by jOOQ.
 */
package com.awscclpu.mailingservice.jooq.tables.daos;


import com.awscclpu.mailingservice.constant.MailingType;
import com.awscclpu.mailingservice.constant.Role;
import com.awscclpu.mailingservice.jooq.tables.Users;
import com.awscclpu.mailingservice.jooq.tables.records.UsersRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersDao extends DAOImpl<UsersRecord, com.awscclpu.mailingservice.jooq.tables.pojos.Users, Long> {

    /**
     * Create a new UsersDao without any configuration
     */
    public UsersDao() {
        super(Users.USERS, com.awscclpu.mailingservice.jooq.tables.pojos.Users.class);
    }

    /**
     * Create a new UsersDao with an attached configuration
     */
    public UsersDao(Configuration configuration) {
        super(Users.USERS, com.awscclpu.mailingservice.jooq.tables.pojos.Users.class, configuration);
    }

    @Override
    public Long getId(com.awscclpu.mailingservice.jooq.tables.pojos.Users object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Users.USERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchById(Long... values) {
        return fetch(Users.USERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.awscclpu.mailingservice.jooq.tables.pojos.Users fetchOneById(Long value) {
        return fetchOne(Users.USERS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchOptionalById(Long value) {
        return fetchOptional(Users.USERS.ID, value);
    }

    /**
     * Fetch records that have <code>active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchRangeOfActive(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Users.USERS.ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchByActive(Boolean... values) {
        return fetch(Users.USERS.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchByEmail(String... values) {
        return fetch(Users.USERS.EMAIL, values);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public com.awscclpu.mailingservice.jooq.tables.pojos.Users fetchOneByEmail(String value) {
        return fetchOne(Users.USERS.EMAIL, value);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public Optional<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchOptionalByEmail(String value) {
        return fetchOptional(Users.USERS.EMAIL, value);
    }

    /**
     * Fetch records that have <code>generated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchRangeOfGeneratedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Users.USERS.GENERATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>generated_at IN (values)</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchByGeneratedAt(LocalDateTime... values) {
        return fetch(Users.USERS.GENERATED_AT, values);
    }

    /**
     * Fetch records that have <code>mailing_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchRangeOfMailingType(MailingType lowerInclusive, MailingType upperInclusive) {
        return fetchRange(Users.USERS.MAILING_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mailing_type IN (values)</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchByMailingType(MailingType... values) {
        return fetch(Users.USERS.MAILING_TYPE, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchByName(String... values) {
        return fetch(Users.USERS.NAME, values);
    }

    /**
     * Fetch records that have <code>password BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchRangeOfPassword(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.PASSWORD, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchByPassword(String... values) {
        return fetch(Users.USERS.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>role BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchRangeOfRole(Role lowerInclusive, Role upperInclusive) {
        return fetchRange(Users.USERS.ROLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchByRole(Role... values) {
        return fetch(Users.USERS.ROLE, values);
    }

    /**
     * Fetch records that have <code>sent_emails BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchRangeOfSentEmails(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Users.USERS.SENT_EMAILS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sent_emails IN (values)</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchBySentEmails(Long... values) {
        return fetch(Users.USERS.SENT_EMAILS, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Users.USERS.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(Users.USERS.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>username BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchRangeOfUsername(String lowerInclusive, String upperInclusive) {
        return fetchRange(Users.USERS.USERNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchByUsername(String... values) {
        return fetch(Users.USERS.USERNAME, values);
    }

    /**
     * Fetch a unique record that has <code>username = value</code>
     */
    public com.awscclpu.mailingservice.jooq.tables.pojos.Users fetchOneByUsername(String value) {
        return fetchOne(Users.USERS.USERNAME, value);
    }

    /**
     * Fetch a unique record that has <code>username = value</code>
     */
    public Optional<com.awscclpu.mailingservice.jooq.tables.pojos.Users> fetchOptionalByUsername(String value) {
        return fetchOptional(Users.USERS.USERNAME, value);
    }
}
