name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mailing_service
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Maven
        run: |
          pwd
          java -version
          ./mvnw --version
          ./mvnw -B package --file pom.xml
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: Mailing-Service-JAR
          path: /home/runner/work/mailing-service/mailing-service/target/*.jar
